### ISSUE TITLE
Help > Keyboard shortcuts does not work

### ISSUE THREAD

**Issue by orting** [Abe404/RootPainter3D#3]
The "Keyboard shortcuts" menu item does not display anything. It prints the following error

Traceback (most recent call last):
  File "main.py", line 80, in <module>
    init_root_painter()
  File "main.py", line 66, in init_root_painter
    exit_code = app_context.app.exec_()
  File "<path-removed>/RootPainter3D/painter/src/main/python/root_painter.py", line 422, in show_shortcut_window
    self.shortcut_window = ShortcutWindow()
  File "<path-removed>/RootPainter3D/painter/src/main/python/about.py", line 798, in __init__
    self.initUI()
  File "<path-removed>/RootPainter3D/painter/src/main/python/about.py", line 859, in initUI
    table.horizontalHeader().sectionSizeFromContents(True)
RuntimeError: no access to protected functions or signals for objects not created from Python

Linux Debian 10
Python 3.7.3
PyQt 5.14.2

Can be solved by removing 
https://github.com/Abe404/RootPainter3D/blob/5d70ea9d6a9498d56d71cb7ad6902ebdc5e2099e/painter/src/main/python/about.py#L859

It then looks like this screenshot.
![Skærmbillede fra 2021-11-15 15-52-00](https://user-images.githubusercontent.com/2413550/141802697-d91c29f1-b4ac-4507-ab92-c1c04393fb05.png)

**Comment by Abe404** [comment]
Fixed in: https://github.com/Abe404/RootPainter3D/commit/2b0dcd93b6e1ccf9de41c94caef0995c90e0a163

This appears to be a linux only bug but it's such a non essential feature that I have just deleted the auto resize to contents line per your suggestion.
